# Generated by Django 2.0.5 on 2018-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleTranlate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translte_str',
            name='english_text',
            field=models.CharField(max_length=5500),
        ),
        migrations.AlterField(
            model_name='translte_str',
            name='tranlate_text',
            field=models.CharField(max_length=5500),
        ),
    ]
