# Generated by Django 2.0.5 on 2018-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleTranlate', '0002_auto_20180518_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='translte_str',
            name='paragraph_id',
            field=models.IntegerField(default=0),
        ),
    ]
